# Generated by Django 5.2.8 on 2025-11-29 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BGVRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('hobbies', models.TextField(blank=True)),
                ('country_of_citizenship', models.CharField(blank=True, max_length=100)),
                ('country_of_residence', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('total_work_experience', models.IntegerField(default=0)),
                ('total_work_experience_months', models.IntegerField(default=0)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('status', models.CharField(choices=[('pending_analysis', 'Pending Analysis'), ('documents_requested', 'Documents Requested'), ('documents_submitted', 'Documents Submitted'), ('completed', 'Completed')], default='pending_analysis', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_bgv_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgv_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('analysis', 'Profile Analysis'), ('request_sent', 'Document Request Sent'), ('reminder_sent', 'Reminder Sent')], max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bgv_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='backgroundverification.bgvrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pan', 'PAN Card'), ('aadhaar', 'Aadhaar Card')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bgv_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='backgroundverification.bgvrequest')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bgv_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='backgroundverification.bgvrequest')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('role_name', models.CharField(blank=True, max_length=200)),
                ('skill_names', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bgv_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='backgroundverification.bgvrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('competency', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bgv_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='backgroundverification.bgvrequest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bgv_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='backgroundverification.bgvrequest')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
