# Generated by Django 5.2.8 on 2025-11-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundverification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgvrequest',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
