# Generated by Django 5.2.8 on 2025-11-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundverification', '0002_alter_bgvrequest_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgvrequest',
            name='country_of_citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bgvrequest',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bgvrequest',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bgvrequest',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bgvrequest',
            name='total_work_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
