# Generated by Django 5.2.8 on 2025-11-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundverification', '0003_alter_bgvrequest_country_of_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='role_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
